version: '3.0'

services:

  frontend:
    container_name: react_app
    image: react_image
    build: ./frontend
    volumes:
      - ./frontend:/frontend  # Montagem de volume para o código do frontend
    ports:
      - "3000:3000"
    command: bash -c "npm install && npm start"

  backend:
    container_name: fastapi_app
    image: fastapi_image
    build: 
      context: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - ./backend/app:/app  # Montagem de volume para o código do backend

  db:
    container_name: mysql
    image: mysql_image
    build: ./db
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: matrix123
      MYSQL_DATABASE: studentdatabase
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
    driver: local