version: '3.0'

services:

  frontend:
    image: react_app_image
    container_name: react_app
    build: ./frontend
    volumes:
      - ./frontend:/frontend  # Montagem de volume para o código do frontend
      - node_modules:/frontend/node_modules  # Montagem de volume para o node_modules
    ports:
      - "3000:3000"

  backend:
    container_name: fastapi_app
    image: fastapi_app_image
    build: 
      context: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - ./backend/app:/app  # Montagem de volume para o código do backend

  db:
    container_name: mysql8
    image: mysql8
    build: ./db
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: matrix123
      MYSQL_DATABASE: studentdatabase
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
    driver: local
  node_modules: